
####################
# 사이트 설정
####################

  title: O.K.T                          # 브라우저 탭과 헤더에 표시될 이름
  description: ver 0.3 ( 2026-04-15 )   # 사이트 설명

  baseurl: "/kunlaboranto"
  url: "https://isuha85.github.io"

# markdown: kramdown

####################
# theme: jekyll-theme-minimal  # 테마 이름 (예: jekyll-theme-slate, jekyll-theme-merlot 등)
####################

####################
# theme: minima
####################
  theme: minima
  author: okseop7 @ gmail.com

